name: xsend
description: Simple command line tool to send files to your phone over Telegram.
version: 1.0.2
publish_to: none
environment:
  sdk: ^3.2.1

dependencies:
  televerse:
    git:
      url: https://github.com/HeySreelal/televerse.git
      ref: single-context

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
