name: xsend
description: Simple command line tool to send files to your phone over Telegram.
version: 1.0.3
publish_to: none
environment:
  sdk: ^3.2.1

dependencies:
  televerse: ^1.16.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
